_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 30
                - 41
                - 49
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.18.7
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
